import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';

pdfMake.vfs = pdfFonts.pdfMake?.vfs || pdfFonts.vfs;

/**
 * Builds a Delivery Challan document matching the client's exact layout:
 *   - Company header (Name, Reg Address, GSTIN, Dispatch Address)
 *   - DELIVERY CHALLAN title
 *   - Challan No / Date header strip
 *   - Bill To / Ship To two-column section
 *   - Dispatch Date & Time / Vehicle No
 *   - Line items table (Sl.No, Item Name, HSN Code, Unit, Quantity, Rate, Amount)
 *   - Terms & Conditions
 *   - Footer: Challan generated by | Dispatch approved by | Received by (Name, Designation, Time In/Out) + Signature & Stamp
 *   - "Computer generated document" note
 */
export function buildInvoiceDoc({ invoice, client, dispatch, grade, companySettings = {} }) {
  const showRate = invoice.showRateOnInvoice !== false;
  const invoiceDate = new Date(invoice.generatedAt || Date.now()).toLocaleDateString('en-IN');
  const dispatchDT = dispatch?.dispatchDateTime
    ? new Date(dispatch.dispatchDateTime).toLocaleString('en-IN')
    : '';

  const quantity = invoice.quantity ?? 0;
  const rate = invoice.rate ?? 0;
  const amount = invoice.amount ?? rate * quantity;

  // Company info from admin-configurable settings
  const companyName = companySettings.companyName || 'COMPANY NAME';
  const regAddress = companySettings.regAddress || '';
  const gstin = companySettings.gstin || '';
  const dispatchAddress = companySettings.dispatchAddress || '';

  // Line items table body
  const tableHeader = [
    { text: 'Sl. No', style: 'tableHead', alignment: 'center' },
    { text: 'ITEM NAME', style: 'tableHead' },
    { text: 'HSN CODE', style: 'tableHead', alignment: 'center' },
    { text: 'UNIT', style: 'tableHead', alignment: 'center' },
    { text: 'QUANTITY', style: 'tableHead', alignment: 'center' },
    ...(showRate
      ? [
          { text: 'RATE', style: 'tableHead', alignment: 'right' },
          { text: 'AMOUNT', style: 'tableHead', alignment: 'right' },
        ]
      : []),
  ];

  const tableRow = [
    { text: '1', alignment: 'center' },
    { text: `Ready Mix Concrete — ${grade?.gradeCode || ''}`, style: 'tableCell' },
    { text: '38120000', alignment: 'center', style: 'tableCell' }, // standard RMC HSN
    { text: 'M³', alignment: 'center', style: 'tableCell' },
    { text: String(quantity), alignment: 'center', style: 'tableCell' },
    ...(showRate
      ? [
          { text: `₹ ${rate.toFixed(2)}`, alignment: 'right', style: 'tableCell' },
          { text: `₹ ${amount.toFixed(2)}`, alignment: 'right', style: 'tableCell', bold: true },
        ]
      : []),
  ];

  const tableWidths = showRate ? [30, '*', 70, 40, 60, 60, 70] : [30, '*', 70, 40, 60];

  return {
    pageSize: 'A4',
    pageMargins: [36, 36, 36, 60],

    content: [
      // ── Company header ──────────────────────────────────────────────
      {
        text: companyName,
        style: 'companyName',
        alignment: 'center',
      },
      {
        alignment: 'center',
        fontSize: 8,
        color: '#444',
        lineHeight: 1.4,
        text: [
          regAddress ? `Reg Address: ${regAddress}\n` : 'Reg Address: \n',
          gstin ? `GSTIN: ${gstin}\n` : 'GSTIN: \n',
          dispatchAddress ? `Dispatch Address: ${dispatchAddress}` : 'Dispatch Address: ',
        ],
      },

      { canvas: [{ type: 'line', x1: 0, y1: 4, x2: 523, y2: 4, lineWidth: 0.5 }] },
      { text: '\n' },

      // ── Challan title ───────────────────────────────────────────────
      {
        text: 'DELIVERY CHALLAN',
        style: 'challantitle',
        alignment: 'center',
        margin: [0, 0, 0, 4],
      },

      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 523, y2: 0, lineWidth: 0.5 }] },

      // ── Challan No / Date row ───────────────────────────────────────
      {
        columns: [
          { text: `Challan No:  ${invoice.invoiceNumber}`, fontSize: 9 },
          { text: `Date: ${invoiceDate}`, fontSize: 9, alignment: 'right' },
        ],
        margin: [0, 6, 0, 6],
      },

      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 523, y2: 0, lineWidth: 0.5 }] },

      // ── Bill To / Ship To ───────────────────────────────────────────
      {
        columns: [
          {
            width: '50%',
            stack: [
              { text: 'Bill to:', fontSize: 8, color: '#666', margin: [0, 6, 0, 2] },
              { text: client?.clientName || '', bold: true, fontSize: 10 },
              { text: client?.officeAddress || '', fontSize: 9, color: '#444' },
              { text: client?.contactNumber || '', fontSize: 9, color: '#444' },
              client?.taxInformation?.gstin
                ? { text: `GSTIN: ${client.taxInformation.gstin}`, fontSize: 9, color: '#444' }
                : {},
            ],
          },
          {
            width: '50%',
            stack: [
              { text: 'Ship to:', fontSize: 8, color: '#666', margin: [0, 6, 0, 2] },
              { text: client?.clientName || '', bold: true, fontSize: 10 },
              {
                text: dispatch?.site?.siteName
                  ? `Site: ${dispatch.site.siteName}`
                  : client?.officeAddress || '',
                fontSize: 9,
                color: '#444',
              },
            ],
          },
        ],
        margin: [0, 0, 0, 8],
        columnGap: 10,
      },

      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 523, y2: 0, lineWidth: 0.5 }] },

      // ── Dispatch Date & Vehicle ─────────────────────────────────────
      {
        columns: [
          { text: `Dispatch Date & Time:  ${dispatchDT}`, fontSize: 9 },
          {
            text: `Vehicle No:  ${dispatch?.vehicleNumber || ''}`,
            fontSize: 9,
            alignment: 'right',
          },
        ],
        margin: [0, 6, 0, 6],
      },

      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 523, y2: 0, lineWidth: 0.5 }] },

      // ── Line items table ────────────────────────────────────────────
      {
        margin: [0, 0, 0, 0],
        table: {
          headerRows: 1,
          widths: tableWidths,
          body: [tableHeader, tableRow, ...Array(4).fill(tableRow.map(() => ({ text: '' })))],
        },
        layout: {
          hLineWidth: (i) => 0.5,
          vLineWidth: (i) => 0.5,
          hLineColor: () => '#999',
          vLineColor: () => '#999',
          fillColor: (row) => (row === 0 ? '#e8e8e8' : null),
          paddingLeft: () => 4,
          paddingRight: () => 4,
          paddingTop: () => 5,
          paddingBottom: () => 5,
        },
      },

      // ── Amount total (only when rate is shown) ──────────────────────
      showRate
        ? {
            margin: [0, 0, 0, 0],
            table: {
              widths: [...tableWidths.slice(0, -1), tableWidths[tableWidths.length - 1]],
              body: [
                [
                  {
                    text: `Total Amount: ₹ ${amount.toFixed(2)}`,
                    colSpan: tableWidths.length,
                    bold: true,
                    alignment: 'right',
                    fontSize: 10,
                  },
                  ...Array(tableWidths.length - 1).fill({}),
                ],
              ],
            },
            layout: {
              hLineWidth: () => 0.5,
              vLineWidth: () => 0.5,
              hLineColor: () => '#999',
              vLineColor: () => '#999',
              paddingLeft: () => 4,
              paddingRight: () => 4,
              paddingTop: () => 4,
              paddingBottom: () => 4,
            },
          }
        : { text: '' },

      // ── Terms & Conditions ──────────────────────────────────────────
      {
        margin: [0, 0, 0, 0],
        table: {
          widths: ['*'],
          body: [
            [{ text: 'Terms & Conditions:', fontSize: 8, bold: true, margin: [2, 2, 2, 0] }],
            [
              {
                text: '1. Goods once dispatched will not be taken back.\n2. Payment due as per agreed credit terms.\n3. Subject to local jurisdiction.',
                fontSize: 7.5,
                color: '#555',
                margin: [2, 0, 2, 6],
              },
            ],
          ],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          hLineColor: () => '#999',
          vLineColor: () => '#999',
          paddingLeft: () => 4,
          paddingRight: () => 4,
          paddingTop: () => 3,
          paddingBottom: () => 3,
        },
      },

      // ── Footer: signatures ──────────────────────────────────────────
      {
        margin: [0, 0, 0, 0],
        table: {
          widths: ['35%', '65%'],
          body: [
            [
              {
                stack: [
                  { text: 'Challan generated by:', fontSize: 8, bold: false },
                  { text: '\n\n\n', fontSize: 8 },
                  { text: 'Dispatch approved by:', fontSize: 8, bold: false },
                  { text: '\n\n', fontSize: 8 },
                ],
                border: [true, true, true, true],
              },
              {
                stack: [
                  { text: 'Received by:', fontSize: 8 },
                  {
                    columns: [
                      { text: 'Name: ________________________', fontSize: 8, margin: [0, 4, 0, 0] },
                    ],
                  },
                  {
                    columns: [
                      {
                        text: 'Designation: __________________',
                        fontSize: 8,
                        margin: [0, 4, 0, 0],
                      },
                    ],
                  },
                  {
                    columns: [
                      {
                        text: 'Time in: _______________',
                        fontSize: 8,
                        width: '50%',
                        margin: [0, 4, 0, 0],
                      },
                      {
                        text: 'Time out: ______________',
                        fontSize: 8,
                        width: '50%',
                        margin: [0, 4, 0, 0],
                      },
                    ],
                  },
                  {
                    text: 'Signature and Stamp',
                    fontSize: 8,
                    alignment: 'right',
                    margin: [0, 10, 4, 0],
                  },
                ],
                border: [true, true, true, true],
              },
            ],
          ],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          hLineColor: () => '#999',
          vLineColor: () => '#999',
          paddingLeft: () => 6,
          paddingRight: () => 6,
          paddingTop: () => 6,
          paddingBottom: () => 6,
        },
      },

      // ── Computer generated notice ───────────────────────────────────
      {
        canvas: [{ type: 'line', x1: 0, y1: 4, x2: 523, y2: 4, lineWidth: 0.5 }],
        margin: [0, 0, 0, 2],
      },
      {
        text: 'This is a computer generated document and does not require a signature',
        fontSize: 7.5,
        color: '#888',
        alignment: 'center',
        margin: [0, 2, 0, 0],
      },
    ],

    styles: {
      companyName: { fontSize: 14, bold: true, color: '#111' },
      challantitle: { fontSize: 14, bold: true, letterSpacing: 1 },
      tableHead: { fontSize: 8, bold: true, color: '#111' },
      tableCell: { fontSize: 9, color: '#222' },
    },

    defaultStyle: { fontSize: 9, font: 'Roboto' },
  };
}

export function generateInvoicePdfBlob(args) {
  return new Promise((resolve) => {
    pdfMake.createPdf(buildInvoiceDoc(args)).getBlob((blob) => resolve(blob));
  });
}

export function openInvoicePdf(args) {
  pdfMake.createPdf(buildInvoiceDoc(args)).open();
}

export function downloadInvoicePdf(args, filename) {
  pdfMake
    .createPdf(buildInvoiceDoc(args))
    .download(filename || `${args.invoice?.invoiceNumber || 'challan'}.pdf`);
}
